### ISSUE TITLE
Coins with date ranges don't display correctly (PCGS)

### ISSUE THREAD

**Issue by dhun1849** [rising-sun-rarities/numisnavigator-public#8]
When importing a coin with a date range, such as "1837-54", only the first date is displayed ie. "1837".

Be careful when addressing, because there are corner cases and implications to "fixing" this.
- Some date ranges will span centuries, such as 1888-12, meaning 1888 to 1912.
- This will make sorting by date a challenge.

I can think of a few ways to make this work, we can discuss.

**Comment by rising-sun-rarities** [comment]
Spanning centuries shouldnt be too difficult unless it spans more than one, in which case I have no idea how that logic could be implemented. 

Another issue is that PCGS API doesnt return the range in the year field, it returns it in the name:

```
"Name":"(1837-54) Bu JNDA 09-50 Tenpo 天 保", 
"Year":1837
```

This shouldnt be too difficult to parse though

**Comment by rising-sun-rarities** [comment]
The best way might be to have the year range stored in the "Year (Other)" field. I previously modified it so that a gregorian year isnt required as long as a "Year (Other)" is input.

I already use the year (other) field for the Meiji year (e.g. an 1870 yen has year as 1870 and year (other) as M9. Sorting that field is doable although it obviously wouldnt be in chronological order

**Comment by rising-sun-rarities** [comment]
I made several changes that addressed this:

1. System parses PCGS API response to pull year, year range, or coins that have two "years" (such as 1870 (M3)
2. Instead of having two separate year fields (year_gregorian and year_other), there is now just one that is in string format
3. Added a sorting handler to parse the first Gregorian year found in the string and sorts by that

commit 562fbcc
